# Generated by Django 5.1.7 on 2025-06-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nota', 'Nota'), ('estadistica', 'Estadística'), ('modelo', 'Modelo Entrenado'), ('reporte', 'Reporte')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='app1.usertable')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
