# Generated by Django 5.1.7 on 2025-06-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contenidorelacionado_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidorelacionado',
            name='titulo',
        ),
    ]
