# Generated by Django 5.1.7 on 2025-06-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_contenidorelacionado_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor_nombre', models.CharField(max_length=100)),
                ('contenedor_pestana', models.CharField(max_length=100)),
                ('contenedor_x', models.IntegerField()),
                ('contenedor_y', models.IntegerField()),
                ('contenedor_ancho', models.IntegerField()),
                ('contenedor_alto', models.IntegerField()),
                ('color_frame', models.CharField(max_length=7)),
                ('borde_redondeado', models.BooleanField()),
                ('numero_borde_redondeado', models.IntegerField()),
                ('textbox_contenido', models.TextField()),
                ('textbox_negrita', models.BooleanField()),
                ('textbox_tamaño_letra', models.IntegerField()),
                ('textbox_capitalizado', models.BooleanField()),
                ('textbox_underline', models.BooleanField()),
                ('textbox_fuente', models.CharField(max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usertable')),
            ],
        ),
    ]
