# Generated by Django 5.1.7 on 2025-06-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_textbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbox',
            name='numero_borde_redondeado',
        ),
        migrations.AlterField(
            model_name='textbox',
            name='borde_redondeado',
            field=models.IntegerField(),
        ),
    ]
