# Generated by Django 5.1.7 on 2025-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_textbox_numero_borde_redondeado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbox',
            name='textbox_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
