# Generated by Django 5.1.7 on 2025-06-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_textbox_textbox_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbox',
            name='textbox_fondo_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
