# Generated by Django 5.1.7 on 2025-06-08 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_textbox_textbox_fondo_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor_nombre', models.CharField(max_length=100)),
                ('contenedor_pestana', models.CharField(max_length=100)),
                ('contenedor_x', models.IntegerField()),
                ('contenedor_y', models.IntegerField()),
                ('contenedor_ancho', models.IntegerField()),
                ('contenedor_alto', models.IntegerField()),
                ('tipo_grafico', models.CharField(max_length=50)),
                ('var_x', models.CharField(blank=True, max_length=100, null=True)),
                ('var_y', models.CharField(max_length=100)),
                ('relleno', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usertable')),
            ],
        ),
    ]
