# Generated by Django 5.1.7 on 2025-06-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_grafico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grafico',
            old_name='color',
            new_name='color_relleno',
        ),
        migrations.RenameField(
            model_name='grafico',
            old_name='relleno',
            new_name='color_texto',
        ),
        migrations.AddField(
            model_name='grafico',
            name='borde_redondeado',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
